(autoload 'doc-mode-next-template               "doc-mode" "" t)
(autoload 'doc-mode-previous-template           "doc-mode" "" t)
(autoload 'doc-mode-first-template              "doc-mode" "" t)
(autoload 'doc-mode                             "doc-mode" "" t)
(autoload 'doc-mode-remove-tag-doc              "doc-mode" "" t)
(autoload 'doc-mode-fix-tag-doc                 "doc-mode" "" t)
(autoload 'doc-mode-check-tag-doc               "doc-mode" "" t)
(autoload 'doc-mode-check-buffer                "doc-mode" "" t)
(autoload 'doc-mode-next-faulty-doc             "doc-mode" "" t)
(autoload 'doc-mode-fold-tag-doc                "doc-mode" "" t)
(autoload 'doc-mode-unfold-doc                  "doc-mode" "" t)
(autoload 'doc-mode-unfold-tag-doc              "doc-mode" "" t)
(autoload 'doc-mode-fold-all                    "doc-mode" "" t)
(autoload 'doc-mode-unfold-all                  "doc-mode" "" t)
(autoload 'doc-mode-toggle-tag-doc-folding      "doc-mode" "" t)
(provide 'code-doc-mode-epkg-install)
